name: Deploy Node.js app on EKS

on:
  push:
    tags:
      - dev-*

env:
  NAMESPACE: amit-dev
  HELM_REPO_NAME: node-app
  ECR_REPO_URL: 884612158688.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  get-version-from-tag:
    runs-on: dev-runner
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

  build-test-push:
    runs-on: dev-runner
    needs: get-version-from-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ECR Repository
        env:
          aws_region: ${{ secrets.DEV_AWS_Region }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
        run: |
          output=$(aws ecr describe-repositories --region $aws_region --repository-names $ECR_REPOSITORY 2>&1)
          if [ $? -ne 0 ]; then
            if echo "${output}" | grep -q RepositoryNotFoundException; then
              aws ecr create-repository --repository-name $ECR_REPOSITORY --region $aws_region
            else
              >&2 echo "${output}"
              exit 1
            fi
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_Region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        env:
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ needs.get-version-from-tag.outputs.VERSION }}
        run: |
          output=$(aws ecr list-images --region ap-south-1 --repository-name $ECR_REPOSITORY | grep latest | tr -d '" ,' | cut -d ':' -f 2)
          echo "Found tag: $output"
          if [[ "$output" == "latest" ]]; then
            docker pull $ECR_REPO_URL/$ECR_REPOSITORY:latest
            docker build --cache-from $ECR_REPO_URL/$ECR_REPOSITORY:latest \
              -t $ECR_REPO_URL/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          else
            docker build -t $ECR_REPO_URL/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          fi

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ needs.get-version-from-tag.outputs.VERSION }}
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
